version: '3.1'

services:
  db:
    image: postgres:latest
    restart: always
    container_name: DB
    environment:
      POSTGRES_DB: GuarantyDatabase
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Guaranty123
    ports:
      - "5432:5432"
    networks:
      - my-network
    volumes:
      - mydbdata:/var/lib/postgresql/data

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: API
    ports:
      - "3000:3000"
    networks:
      - my-network
    depends_on:
      - db

  frontend:
    build:
      context: ./Frontend/guarantymetalui
      dockerfile: Dockerfile
    container_name: FrontEnd
    ports:
      - "80:80"
    networks:
      - my-network
    depends_on:
      - api

networks:
  my-network:
    driver: bridge

volumes:
  mydbdata:
