version: '3.1'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: GuarantyDatabase
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Guaranty123
    ports:
      - "5432:5432"
    volumes:
      - mydbdata:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d

  api:
    build: ./API
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db

  frontend:
    build: ./FrontEnd/GuarantyMetalUi
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  mydbdata:
