version: '3.1'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: GuarantyDatabase
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Guaranty123
    ports:
      - "5432:5432"
    volumes:
      - mydbdata:/var/lib/postgresql/data
      - ./database/sql:/docker-entrypoint-initdb.d

  api:
    build: ./api
    environment:
      DB_HOST: db
      DB_USER: admin
      DB_PASS: Guaranty123
      DB_NAME: GuarantyDatabase
    ports:
      - "3000:3000"
    depends_on:
      - db

  frontend:
    build: ./frontend/guarantymetalui
    restart: always
    ports:
      - "80:80"
    depends_on:
      - api

volumes:
  mydbdata:
