name: Cypress Tests on Test Branch

on:
  push:
    branches:
      - brandon-GithubActionTest
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.11.0' # Adjust the Node.js version as needed for your project

      - name: Install dependencies
        run: npm install
      
      - name: Run Cypress tests
        uses: cypress-io/github-action@v2
        with:
          start: |
            cd FrontEnd/guarantymetalui && npm start
          wait-on: https://localhost
          wait-on-timeout: 300 # Adjust the timeout based on your application's start-up time
        env:
          CI: true
