name: Cypress Tests on Test Branch

on:
  push:
    branches:
      - brandon-GithubActionTest
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      #- name: Setup Node.js
      #  uses: actions/setup-node@v2
      #  with:
      #    node-version: '20.11.0' # Adjust the Node.js version as needed for your project

      #- name: Install dependencies
      #  run: npm install

      - name: Create .env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: Setting Permissions
        run: chmod +x ./nginx/startup.sh && chmod +x ./nginx/generate-certs.sh 

      - name: Starting Docker Compose
        run: docker-compose up --build -d

      - name: Display Nginx logs
        run: docker logs Nginx

      #- name: Wait for services to be ready
      #  run: |
      #    until curl --output /dev/null --silent --head --fail --insecure https://localhost; do
      #      printf '.'
      #      sleep 5
      #    done

      #- name: Running Cypress Command
      #  run: |
      #    cd FrontEnd/guarantymetalui
      #    npx cypress run --spec "./cypress/e2e/*.cy.js"
      
      - name: Run Cypress tests
        uses: cypress-io/github-action@v2
        with:
          working-directory: FrontEnd/guarantymetalui
          wait-on: https://localhost
          wait-on-timeout: 60 # Adjust the timeout based on your application's start-up time
          config-file: cypress.config.js
        env:
          CI: true
