name: Cypress Test

on:
  #push:
  #  branches:
  #    - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  cypress_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Create .env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: Setting Permissions
        run: chmod +x ./nginx/startup.sh && chmod +x ./nginx/generate-certs.sh 

      - name: Starting Docker Compose
        run: docker-compose up --build -d

      - name: Display Nginx logs
        run: docker logs Nginx

      - name: Wait for services to be ready
        run: |
          until curl --output /dev/null --silent --head --fail --insecure https://localhost; do
            printf '.'
            sleep 5
          done

      - name: Running Cypress Command
        run: |
          cd FrontEnd/guarantymetalui
          npx cypress run --spec "./cypress/e2e/*.cy.js"
