name: Deploy to Production Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Add SSH host key
      run: |
        mkdir -p ~/.ssh
        echo "$SERVER_HOST_KEY" >> ~/.ssh/known_hosts
        chmod 600 ~/.ssh/known_hosts
      env:
        SERVER_HOST_KEY: ${{ secrets.SERVER_HOST_KEY }}

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Test directory change
      run: ssh "Brandon Bejarano"@gsminventory.com "cd C:\\Users\\Brandon Bejarano\\Documents\\GitHub\\Guaranty_Sheet_Metal && echo 'Directory Changed Successfully'"
      
    - name: Deploy to Server
      run: |
        ssh "Brandon Bejarano"@gsminventory.com "echo 'Connection Successful'"
        ssh "Brandon Bejarano"@gsminventory.com "cd C:\\Users\\Brandon Bejarano\\Documents\\GitHub\\Guaranty_Sheet_Metal; docker-compose down; git pull; docker-compose -f docker-compose.production.yml up --build -d"
        
