name: Deploy to Production Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:  
    - name: Deploy to Server
      run: |
        "echo 'Connection Successful'"
        cd "C:\\Users\\Brandon Bejarano\\Documents\\GitHub\\Guaranty_Sheet_Metal"
        docker ps
        docker-compose down
        "echo 'Containers Shutdown Successfully'"
        git pull
        "echo 'Updated Main Successfully'"
        docker-compose -f docker-compose.production.yml up --build -d
        "echo 'Updated Containers Successfully'"
        
